[package]
name = "throttler-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.6.0"
redis_rs = "0.9.0"
sqlx = "0.7.1"
tokio = "1.29.1"
